version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: dd-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    image: mfanidham/dd-backend:latest
    container_name: dd-backend
    restart: always
    depends_on:
      - mongo
    environment:
      # same DB name you used earlier: dd_db
      MONGO_URL: "mongodb://mongo:27017/dd_db"
    expose:
      - "8080"   # backend is visible inside Docker network

  frontend:
    image: mfanidham/dd-frontend:latest
    container_name: dd-frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "80"     # frontend is visible inside Docker network

  nginx:
    image: nginx:alpine
    container_name: dd-nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"  # only public port = 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data:
